---
- name: Create the /etc/gitlab/gitlab.rb file
  template:
    src: templates/redis.gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
  tags:
    - gitlab_template

- name: Download secrets file
  shell: "gsutil cp gs://{{ gitlab_conf_storage }}/gitlab-secrets.json /etc/gitlab/gitlab-secrets.json 2>/dev/null || true"
  tags: secrets

- name: Reconfigure GitLab
  shell: gitlab-ctl reconfigure
  tags:
    - reconfigure

- name: Upload secrets file if missing
  shell: "gsutil cp -n /etc/gitlab/gitlab-secrets.json gs://{{ gitlab_conf_storage }}"
  tags: secrets
  run_once: true

- name: Create skip-auto-reconfigure file
  file:
    path: /etc/gitlab/skip-auto-reconfigure
    state: touch
    mode: u=rw,g=r,o=r