---
- name: Install python-consul python package
  pip:
    name: python-consul==1.1.0
  become: true
  tags:
    - prometheus_consul_services

- name: Register Prometheus Consul services with the local consul agent
  community.general.consul:
    service_name: '{{ item.service }}'
    service_port: '{{ item.port }}'
  loop: "{{ prometheus_exporters }}"
  tags:
    - prometheus_consul_services
