---
- name: Create the /etc/gitlab/gitlab.rb file
  template:
    src: templates/pgbouncer.gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
  tags: gitlab_template

- name: Reconfigure GitLab
  shell: gitlab-ctl reconfigure
  retries: 2
  tags: reconfigure

- name: Create .pgpass file
  command: gitlab-ctl write-pgpass --host 127.0.0.1 --database pgbouncer --hostuser gitlab-consul
  args:
    stdin: "{{ pgbouncer_password }}\n{{ pgbouncer_password }}\n"
    creates: /var/opt/gitlab/postgresql/.pgpass
  become: yes

# Bug - https://gitlab.com/gitlab-org/omnibus-gitlab/issues/3448
- name: Restart Consul
  command: gitlab-ctl restart consul

- name: Create skip-auto-reconfigure file
  file:
    path: /etc/gitlab/skip-auto-reconfigure
    state: touch
    mode: u=rw,g=r,o=r