---
  - name: Setup GitLab config file
    template:
      src: templates/praefect.gitlab.rb.j2
      dest: /etc/gitlab/gitlab.rb
    tags: reconfigure
  
  - name: Download secrets file
    shell: "gsutil cp gs://{{ gitlab_secrets_storage }}/gitlab-secrets.json /etc/gitlab/gitlab-secrets.json 2>/dev/null || true"
    tags: secrets
  
  - name: Reconfigure Praefect
    shell: gitlab-ctl reconfigure
    register: result
    retries: 2
    until: result is success
    tags: reconfigure
  
  - name: Restart Praefect
    command: gitlab-ctl restart
    register: result
    retries: 2
    until: result is success
    tags:
      - reconfigure
      - restart
  
  - name: Upload secrets file if missing
    shell: "gsutil cp -n /etc/gitlab/gitlab-secrets.json gs://{{ gitlab_secrets_storage }}"
    tags: secrets
    run_once: true
  
  - name: Create skip-auto-reconfigure file
    file:
      path: /etc/gitlab/skip-auto-reconfigure
      state: touch
      mode: u=rw,g=r,o=r