---
- name: Mount GitLab NFS
  mount:
    fstype: nfs
    opts: defaults,nofail,lookupcache=positive
    state: mounted
    src: "{{ gitlab_nfs_int_ip }}:{{ gitlab_nfs_path }}"
    path: "{{ gitlab_nfs_path }}"
  tags: nfs

- name: Setup GitLab config file
  template:
    src: templates/praefect.gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
  tags: reconfigure

- name: Copy secrets file from NFS
  shell: "cp {{ gitlab_nfs_path }}/gitlab-secrets.json /etc/gitlab/gitlab-secrets.json 2>/dev/null || true"
  tags: secrets

- name: Check if Database is available for Praefect
  shell: /opt/gitlab/embedded/bin/psql -U gitlab-psql -d gitlabhq_production -h {{ praefect_postgres_int_ip }} -c "SELECT 1 FROM pg_roles WHERE rolname='praefect';"
  register: praefect_database_check_result
  when: "'praefect_primary' in group_names"
  tags: database

- name: Setup Database on Postgres
  shell: |
    /opt/gitlab/embedded/bin/psql -U gitlab-psql -d gitlabhq_production -h {{ praefect_postgres_int_ip }} -c "CREATE ROLE {{ praefect_postgres_username }} WITH LOGIN CREATEDB PASSWORD '{{ praefect_postgres_password }}';"
    /opt/gitlab/embedded/bin/psql -U {{ praefect_postgres_username }} -d gitlabhq_production -h {{ praefect_postgres_int_ip }} -c "CREATE DATABASE {{ praefect_postgres_dbname }} WITH ENCODING=UTF8;"
  when:
    - "'praefect_primary' in group_names"
    - "'(0 rows)' in praefect_database_check_result.stdout"
  tags: database

- name: Reconfigure Praefect
  shell: gitlab-ctl reconfigure
  register: result
  retries: 2
  until: result is success
  tags: reconfigure

- name: Restart Praefect
  command: gitlab-ctl restart
  register: result
  retries: 2
  until: result is success
  tags:
    - reconfigure
    - restart

- name: Copy secrets file to NFS if missing
  shell: "cp -n /etc/gitlab/gitlab-secrets.json {{ gitlab_nfs_path }}"
  tags: secrets
  run_once: true

- name: Create skip-auto-reconfigure file
  file:
    path: /etc/gitlab/skip-auto-reconfigure
    state: touch
    mode: u=rw,g=r,o=r
