---
- name: Copy secrets file from NFS
  shell: "cp {{ gitlab_nfs_path }}/gitlab-secrets.json /etc/gitlab/gitlab-secrets.json 2>/dev/null || true"
  tags: secrets

- name: External database related tasks
  block:
    - name: Setup Praefect deploy node config file with DB Migrations
      template:
        src: templates/praefect.gitlab.rb.j2
        dest: /etc/gitlab/gitlab.rb
      vars:
        db_migrate: true
      tags:
        - reconfigure
        - db_migrate

    - name: Reconfigure Praefect deploy node
      shell: gitlab-ctl reconfigure
      register: result
      retries: 3
      until: result is success
      tags:
        - reconfigure
        - db_migrate
  when: "'praefect_postgres' in groups"
  run_once: true

- name: Setup all Praefect config files
  template:
    src: templates/praefect.gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
  register: result
  retries: 3
  until: result is success
  tags: reconfigure

- name: Reconfigure all Praefects
  shell: gitlab-ctl reconfigure
  register: result
  retries: 2
  until: result is success
  tags: reconfigure

- name: Restart all Praefects
  command: gitlab-ctl restart
  register: result
  retries: 2
  until: result is success
  tags:
    - reconfigure
    - restart

- name: Copy secrets file to NFS if missing
  shell: "cp -n /etc/gitlab/gitlab-secrets.json {{ gitlab_nfs_path }}"
  tags: secrets
  run_once: true

- name: Create skip-auto-reconfigure file
  file:
    path: /etc/gitlab/skip-auto-reconfigure
    state: touch
    mode: u=rw,g=r,o=r
