---
- name: Mount GitLab NFS
  mount:
    fstype: nfs
    opts: defaults,nofail,lookupcache=positive
    state: mounted
    src: "{{ gitlab_nfs_int_ip }}:{{ gitlab_nfs_path }}"
    path: "{{ gitlab_nfs_path }}"
  tags: nfs

- name: Configure SSH Fast Lookup
  blockinfile:
    path: /etc/ssh/sshd_config
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      Match User git   # Apply the AuthorizedKeysCommands to the git user only
        AuthorizedKeysCommand /opt/gitlab/embedded/service/gitlab-shell/bin/gitlab-shell-authorized-keys-check git %u %k
        AuthorizedKeysCommandUser git
      Match all        # End match, settings apply to all users again

- name: Create SSH directory on GitLab NFS if missing
  file:
    path: "{{ gitlab_nfs_path }}/ssh"
    state: directory
  when: "'gitlab_rails_primary' in group_names"
  tags: ssh

- name: Copy SSH keys to NFS if missing
  shell: "cp -n /etc/ssh/ssh_host_*_key* {{ gitlab_nfs_path }}/ssh"
  when: "'gitlab_rails_primary' in group_names"
  tags: ssh

- name: Copy SSH keys from NFS
  shell: "cp {{ gitlab_nfs_path }}/ssh/ssh_host_*_key* /etc/ssh"
  when: "'gitlab_rails_secondary' in group_names"
  tags: ssh

- name: Reload SSH service
  service:
    name: ssh
    state: reloaded
  tags: ssh

- name: Copy secrets file from NFS
  shell: "cp {{ gitlab_nfs_path }}/gitlab-secrets.json /etc/gitlab/gitlab-secrets.json 2>/dev/null || true"
  tags: secrets

- name: Copy GCP service account file
  copy:
    src: "{{ gcp_service_account_host_file }}"
    dest: "{{ gcp_service_account_target_file }}"
    mode: 0755
  tags:
    - reconfigure
    - secrets
  when:
    - cloud_provider == 'gcp'

- name: Check if custom config exists
  stat:
    path: "{{ gitlab_rails_custom_config_file }}"
  delegate_to: localhost
  become: false
  tags: reconfigure
  register: gitlab_rails_custom_config_file_path

- name: Get Omnibus Postgres Primary
  block:
    - name: Get latest Postgres primary
      command: gitlab-ctl get-postgresql-primary
      register: postgres_leader_int_address
      delegate_to: "{{ groups['postgres'][0] }}"
      delegate_facts: true
      become: true

    - name: Update Postgres primary IP and Port
      set_fact:
        postgres_host: "{{ postgres_leader_int_address.stdout.split(':')[0] }}"
        postgres_port: "{{ postgres_leader_int_address.stdout.split(':')[1] }}"
  when:
    - "'postgres' in groups and groups['postgres'] | length > 1"
    - postgres_replication_manager == 'patroni'
  tags:
    - reconfigure
    - db_migrate

- name: Non Omnibus database related tasks
  block:
    - name: Create Database User
      community.postgresql.postgresql_user:
        login_host: "{{ postgres_host }}"
        login_port: "{{ postgres_port }}"
        login_user: "{{ postgres_admin_username }}"
        login_password: "{{ postgres_admin_password }}"
        db: "template1"
        name: "{{ postgres_username.split('@')[0] }}"
        password: "{{ postgres_password }}"
        role_attr_flags: CREATEDB
        expires: infinity

    - name: Create Database
      community.postgresql.postgresql_db:
        login_host: "{{ postgres_host }}"
        login_port: "{{ postgres_port }}"
        login_user: "{{ postgres_username }}"
        login_password: "{{ postgres_password }}"
        name: "{{ postgres_database_name }}"
        encoding: UTF-8

    - name: Enable required Postgres extensions
      community.postgresql.postgresql_ext:
        login_host: "{{ postgres_host }}"
        login_port: "{{ postgres_port }}"
        login_user: "{{ postgres_admin_username }}"
        login_password: "{{ postgres_admin_password }}"
        name: "{{ item }}"
        db: "{{ postgres_database_name }}"
      loop: ['pg_trgm', 'btree_gist', 'plpgsql']
  when: postgres_external
  tags:
    - reconfigure
    - db_migrate
    - postgres_external
  run_once: true

- name: Run Database Migrations
  block:
    - name: Setup GitLab deploy node config file with DB Migrations
      template:
        src: templates/gitlab-rails.gitlab.rb.j2
        dest: /etc/gitlab/gitlab.rb
      vars:
        db_migrate: true
      tags:
        - reconfigure
        - db_migrate

    - name: Copy custom GitLab config file
      copy:
        src: "{{ gitlab_rails_custom_config_file }}"
        dest: "/etc/gitlab/gitlab.gitlab_rails.custom.rb"
        mode: 0644
      tags:
        - reconfigure
        - db_migrate
      when: gitlab_rails_custom_config_file_path.stat.exists

    - name: Reconfigure GitLab deploy node
      shell: gitlab-ctl reconfigure
      register: result
      retries: 3
      until: result is success
      tags:
        - reconfigure
        - db_migrate
  run_once: true

- name: Setup all GitLab Rails config files
  template:
    src: templates/gitlab-rails.gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
  register: result
  retries: 3
  until: result is success
  tags: reconfigure

- name: Copy custom GitLab config file
  copy:
    src: "{{ gitlab_rails_custom_config_file }}"
    dest: "/etc/gitlab/gitlab.gitlab_rails.custom.rb"
    mode: 0644
  tags: reconfigure
  when: gitlab_rails_custom_config_file_path.stat.exists

- name: Reconfigure all GitLab Rails
  shell: gitlab-ctl reconfigure
  register: result
  retries: 3
  until: result is success
  tags: reconfigure

- name: Restart GitLab
  shell: gitlab-ctl stop && gitlab-ctl start
  register: result
  retries: 2
  until: result is success
  tags:
    - reconfigure
    - restart

- name: Copy secrets file to NFS if missing
  shell: "cp -n /etc/gitlab/gitlab-secrets.json {{ gitlab_nfs_path }}"
  tags: secrets
  run_once: true

- name: Create skip-auto-reconfigure file
  file:
    path: /etc/gitlab/skip-auto-reconfigure
    state: touch
    mode: u=rw,g=r,o=r

- name: Enable Feature Flags
  shell: |
    gitlab-rails runner "Feature.enable(:{{ item }})"
  loop: "{{ gitlab_rails_feature_flags }}"
  run_once: true
