stages:
  - check

#########################
##     Lint Checks     ##
#########################

check:tflint:
  stage: check
  image: alpine
  before_script:
    - apk add curl
    - curl -L "$(curl -Ls https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" -o tflint.zip && unzip tflint.zip -d /usr/bin
  script:
    - |
      tflint --init
      cd terraform/modules
      for dir in */; do
        echo "************************************************************************"
        echo "Executing tflint for module: $dir"
        echo "************************************************************************"
        tflint -c ${CI_PROJECT_DIR}/.tflint.hcl $dir
      done
  only:
    - master
    - merge_requests
  except:
    - schedules
    - tags

check:ansible-lint:
  stage: check
  image: quay.io/ansible/toolset
  script:
    - chmod 700 ansible
    - cd ansible
    - ansible-lint
  only:
    - master
    - merge_requests
  except:
    - schedules
    - tags