stages:
  - start
  - provision
  - configure
  - stop

.update-base:
  image: alpine
  before_script:
    - echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
    - apk add -u --no-cache git-crypt
    - echo "$GIT_CRYPT_KEY" | base64 -d > /tmp/git-crypt.key
    - git-crypt unlock /tmp/git-crypt.key
    - chmod 600 keys/performance/gitlab-qa-gcp-ssh
  variables:
    GCLOUD_SERVICEACCOUNT_KEY_PATH: keys/performance/serviceaccount-$ENVIRONMENT_NAME.json
  only:
    - schedules

start:
  extends: .update-base
  image: google/cloud-sdk:alpine
  stage: start
  script:
    - unset CLOUDSDK_CORE_PROJECT
    - gcloud auth activate-service-account --key-file=$GCLOUD_SERVICEACCOUNT_KEY_PATH
    - gcloud config set project $GCP_PROJECT_NAME
    - echo "Starting VMs on GCP project '$GCP_PROJECT_NAME'"
    - gcloud compute instances start --zone $GCLOUD_ZONE $(gcloud compute instances list --format='value(name)' --filter="labels.gitlab_node_prefix ~ $GCP_GITLAB_NODE_PREFIX$")
    - sleep 60
  only:
    variables:
      - $ENVIRONMENT_ACTION == "start" || $ENVIRONMENT_ACTION == "update"

terraform:
  extends: .update-base
  stage: provision
  variables:
    TERRAFORM_VERSION: "0.12.18"
  script:
    - apk add -u --no-cache wget unzip
    - wget -q -P /tmp/ https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
    - unzip /tmp/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/bin
    - cd terraform/$ENVIRONMENT_NAME
    - terraform init
    - terraform apply -auto-approve
    - sleep 20
  only:
    variables:
      - $ENVIRONMENT_ACTION == "update"

ansible:
  extends: .update-base
  stage: configure
  script:
    - apk add -u --no-cache build-base openssh-client ca-certificates ansible tar py3-pip python3-dev
    - chmod 700 ansible
    - cd ansible
    - pip3 install -r requirements/ansible-python-packages.txt
    - ansible-galaxy install -r requirements/ansible-roles.yml
    - ansible-playbook -i inventories/$ENVIRONMENT_NAME all.yml
  only:
    variables:
      - $ENVIRONMENT_ACTION == "update"

stop:
  extends: .update-base
  image: google/cloud-sdk:alpine
  stage: stop
  script:
    - unset CLOUDSDK_CORE_PROJECT
    - gcloud auth activate-service-account --key-file=$GCLOUD_SERVICEACCOUNT_KEY_PATH
    - gcloud config set project $GCP_PROJECT_NAME
    - echo "Stopping VMs on GCP project '$GCP_PROJECT_NAME'"
    - gcloud compute instances stop --zone $GCLOUD_ZONE $(gcloud compute instances list --format='value(name)' --filter="labels.gitlab_node_prefix ~ $GCP_GITLAB_NODE_PREFIX$ AND -name ~ monitor-|haproxy-external-\d+$")
  only:
    variables:
      - $ENVIRONMENT_ACTION == "stop"
