include:
  - template: Dependency-Scanning.gitlab-ci.yml

stages:
  - test
  - build

#########################
##     Lint Checks     ##
#########################

check:terraform-fmt:
  stage: test
  image:
    name: "hashicorp/terraform"
    entrypoint: [ "" ]
  before_script:
    - terraform version
  script:
    - terraform fmt -check -recursive -diff terraform/
  only:
    - master
    - merge_requests
  except:
    - schedules
    - tags

check:tflint:
  stage: test
  image: alpine
  before_script:
    - apk add curl
    - curl -L "$(curl -Ls https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" -o tflint.zip && unzip tflint.zip -d /usr/bin
  script:
    - |
      set +e
      tflint --init
      cd terraform/modules

      RESULT=0

      for dir in */; do
        echo "************************************************************************"
        echo "Executing tflint for module: $dir"
        echo "************************************************************************"
        tflint -c ${CI_PROJECT_DIR}/.tflint.hcl $dir
        status=$?
        if [ $status -gt 0 ]; then
          RESULT=$status
        fi
      done

      exit $RESULT
  only:
    - master
    - merge_requests
  except:
    - schedules
    - tags

check:ansible-lint:
  stage: test
  image: quay.io/ansible/toolset
  script:
    - chmod 700 ansible
    - cd ansible
    - ansible-lint
  only:
    - master
    - merge_requests
  except:
    - schedules
    - tags

# Does the requirements.txt install?
check_requirements:
  stage: test
  image: python:3
  script:
    - python -m venv get-python-env
    - source ./get-python-env/bin/activate
    - pip install -r ansible/requirements/requirements.txt
    - ansible-galaxy install -r ansible/requirements/ansible-galaxy-requirements.yml
  rules:
    - changes:
        - ansible/requirements/requirements.txt
        - ansible/requirements/ansible-galaxy-requirements.yml

build_image:
  stage: build
  image: docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
  services:
    - name: docker:dind
      alias: localhost
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t ${CI_REGISTRY_IMAGE}:without-get-user .
    - docker push ${CI_REGISTRY_IMAGE}:without-get-user
