---
# - name: Mount GitLab NFS
#   mount:
#     fstype: nfs
#     opts: defaults,nofail,lookupcache=positive
#     state: mounted
#     src: "{{ gitlab_nfs_int_ip }}:{{ gitlab_nfs_path }}"
#     path: "{{ gitlab_nfs_path }}"
#   tags: nfs

- name: Configure SSH Fast Lookup
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^{{ item.setting }}="
    line: "{{ item.setting }}={{ item.value }}"
  with_items: 
    - { setting: 'AuthorizedKeysCommand', value: '/opt/gitlab/embedded/service/gitlab-shell/bin/gitlab-shell-authorized-keys-check git %u %k'}
    - { setting: 'AuthorizedKeysCommandUser', value: 'git'}

- name: Setup GitLab config file
  template:
    src: templates/sidekiq.gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
  tags: reconfigure

- name: Download secrets files
  shell: |
    gsutil cp gs://{{ gitlab_secrets_storage }}/gitlab-secrets.json /etc/gitlab/gitlab-secrets.json 2>/dev/null || true
    gsutil cp gs://{{ gitlab_secrets_storage }}/{{ serviceaccount_filename }} {{ serviceaccount_path }} 2>/dev/null || true
  tags: secrets

- name: Reconfigure Sidekiq
  shell: gitlab-ctl reconfigure
  tags:
    - reconfigure

- name: Restart Sidekiq
  command: gitlab-ctl restart
  register: result
  retries: 2
  until: result is success
  tags:
    - reconfigure
    - restart
    
#- name: Hot Reload Sidekiq 
#  shell: gitlab-ctl hup sidekiq
#  tags: reload

- name: Upload secrets file if missing
  shell: "gsutil cp -n /etc/gitlab/gitlab-secrets.json gs://{{ gitlab_secrets_storage }}"
  tags: secrets
  run_once: true

- name: Create skip-auto-reconfigure file
  file:
    path: /etc/gitlab/skip-auto-reconfigure
    state: touch
    mode: u=rw,g=r,o=r
