plugin: gcp_compute
projects:
  - group-geo-f9c951
filters:
  - labels.gitlab_cluster_name = "geo-ash3-10k"  # TODO: CHANGEME
  - labels.gitlab_geo_role = "primary" # TODO: CHANGEME
  # - labels.gitlab_geo_role = "secondary" # TODO: CHANGEME
keyed_groups:
  - key: labels.gitlab_node_type
    separator: ''
  - key: labels.gitlab_node_level
    separator: ''
  - prefix: geo_role
    key: labels.gitlab_geo_role
    separator: '_'

scopes:
  - https://www.googleapis.com/auth/compute
service_account_file: ../secrets/group-geo-f9c951-b5620cc0bf35.json
auth_kind: serviceaccount
hostnames:
  # List host by name instead of the default public ip
  - name
compose:
  # Set an inventory parameter to use the Public IP address to connect to the host
  # For Private ip use "networkInterfaces[0].networkIP"
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
