---
- name: Check Omnibus data volume {{ data_disk }} avialable
  stat:
    path: "{{ data_disk }}"
  register: data_disk_info
  when: data_disk is defined

- name: Mount volume if data volume exists
  block:
    - name: Create ext4 filesystem {{ data_disk }}
      filesystem:
        fstype: ext4
        dev: "{{ data_disk }}"

    - name: Create mount point for Omnibus data volume
      file:
        path: /var/opt/gitlab
        state: directory
      when:
        - omnibus_node

    - name: Mount Omnibus data volume
      mount:
        path: /var/opt/gitlab
        src: "{{ data_disk }}"
        fstype: ext4
        state: mounted
      when:
        - omnibus_node

    - name: Create mount point for elastic data volume
      file:
        path: /var/lib/docker
        state: directory
      when:
        - ('elastic' in group_names)

    - name: Mount elastic data volume
      mount:
        path: /var/lib/docker
        src: "{{ data_disk }}"
        fstype: ext4
        state: mounted
      when:
        - ('elastic' in group_names)
  when:
    - data_disk is defined
    - data_disk_info.stat.exists
