---

- name: Stat the disks
  stat:
    path: "{{ disk_device_prefix[cloud_provider] }}{{ item.device_name }}"
  register: disks_info
  loop: "{{ disk_mounts }}"

- name: Create and mount disks
  block:
    - name: Create ext4 filesystem
      filesystem:
        fstype: ext4
        dev: "{{ disk_device_prefix[cloud_provider] }}{{ item.device_name }}"
        opts: "{{ mkfs_opts }}"
      loop: "{{ disk_mounts }}"
      loop_control:
        index_var: loop_index

    # Device names may change on reboot so it is always best to use
    # the UUID of disks in /etc/fstab
    - name: Get the UUID for the device
      command: "blkid -s UUID -o value {{ disk_device_prefix[cloud_provider] }}{{ item.device_name }}"
      register: device_uuids
      loop: "{{ disk_mounts }}"
      changed_when: false
      loop_control:
        index_var: loop_index

    - name: Create directory for mount
      file:
        path: "{{ item.mount_dir }}"
        state: directory
        mode: '0755'
      loop: "{{ disk_mounts }}"
      loop_control:
        index_var: loop_index

    - name: Mount the disk
      mount:
        path: "{{ item.mount_dir }}"
        src: "UUID={{ device_uuids.results[loop_index].stdout }}"
        fstype: ext4
        state: mounted
        opts: "{{ mount_opts }}"
      loop: "{{ disk_mounts }}"
      loop_control:
        index_var: loop_index
  when: disks_info.results[loop_index].stat.exists
