---
- name: Install system packages
  apt:
    name: ['aptitude', 'curl', 'openssh-server', 'ca-certificates', 'glances', 'nano', 'tzdata', 'postfix',
           'ack-grep', 'tree', 'python-pip', 'python3-pip', 'nfs-common']
    update_cache: yes
  tags: packages

- name: Install python packages
  pip:
    name:
    - requests
    - google-auth
    - netaddr
  tags: packages

- name: Check if GitLab is already installed
  stat: path=/usr/bin/gitlab-ctl
  register: gitlab_file
  tags: always
  when: install_gitlab

- name: Download GitLab repository installation script
  get_url:
    url: "{{ gitlab_repo_script_url }}"
    dest: /tmp/gitlab_install_repository.sh
    force: yes
  register: repo_file
  when:
    - install_gitlab

- name: Install GitLab repository
  command: bash /tmp/gitlab_install_repository.sh
  when:
    - install_gitlab
    - repo_file.changed

- name: Uninstall GitLab package
  command: "{{ item }}"
  args:
    warn: false
  with_items:
    - apt-mark install gitlab-ee
    - apt-get remove gitlab-ee -y
  when:
    - uninstall_gitlab | bool

- name: Install GitLab package
  command: "{{ item }}"
  with_items:
    - apt-mark install gitlab-ee
    - apt-get install {{ gitlab_package }}={{ gitlab_package_version }} -y --allow-downgrades
    - apt-mark hold gitlab-ee
  args:
    warn: false
  when:
    - install_gitlab
    - gitlab_package is defined

- name: Update system packages to the latest version
  apt:
    upgrade: 'safe'
  register: result
  retries: 1
  until: result is success
