---
- name: Install system packages
  apt:
    name: ['aptitude', 'curl', 'openssh-server', 'ca-certificates', 'glances', 'nano', 'tzdata', 'postfix',
           'ack-grep', 'tree', 'python-pip', 'python3-pip', 'nfs-common']
    update_cache: yes
  tags: packages

- name: Install python packages
  pip:
    name: 
    - requests
    - google-auth
    - netaddr
  tags: packages

- name: Download GitLab repository installation script
  get_url:
    url: "{{ gitlab_repo_script_url }}"
    dest: /tmp/gitlab_install_repository.sh
    force: yes
  register: repo_file
  when: 
    - install_gitlab

- name: Install GitLab repository
  command: bash /tmp/gitlab_install_repository.sh
  when: 
    - install_gitlab
    - repo_file.changed

- name: Uninstall GitLab package
  command: "{{ item }}"
  args:
    warn: false
  with_items:
    - apt-mark install gitlab-ee
    - apt-get remove gitlab-ee -y
  when:
    - install_gitlab
    - uninstall_gitlab

- name: Unlock GitLab package updates
  command: apt-mark install gitlab-ee
  when: 
    - install_gitlab
  
- name: Install GitLab repo package
  command: apt-get install {{ gitlab_repo_package }} -y --allow-downgrades
  args:
    warn: false
  when: 
    - install_gitlab
    - gitlab_repo_package != ''
    - gitlab_deb_package == ''

- name: Install GitLab deb package
  apt:
    deb: "{{ gitlab_deb_package }}"
  when: 
    - install_gitlab
    - gitlab_deb_package != ''

- name: Lock GitLab package updates
  command: apt-mark hold gitlab-ee
  when: 
    - install_gitlab

- name: Update system packages to the latest version
  apt:
    upgrade: 'safe'
  register: result
  retries: 1
  until: result is success
