---
- name: Install system packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items: '{{ common_apt_packages }}'
  tags: packages

- name: Install python packages
  pip:
    name:
    - requests
    - google-auth
    - netaddr
  tags: packages

- name: Check if GitLab is already installed
  stat: path=/usr/bin/gitlab-ctl
  register: gitlab_file
  tags: always
  when: install_gitlab

- name: Download GitLab repository installation script
  get_url:
    url: "{{ gitlab_repo_script_url }}"
    dest: /tmp/gitlab_install_repository.sh
    force: yes
  register: repo_file
  when:
    - install_gitlab

- name: Install GitLab repository
  command: bash /tmp/gitlab_install_repository.sh
  when:
    - install_gitlab
    - repo_file.changed

- name: Install GitLab package
  apt:
    name: gitlab-ee
    update_cache: yes
  when:
    - install_gitlab
    - not gitlab_file.stat.exists

- name: Update all packages to the latest version
  apt:
    upgrade: 'safe'
  register: result
  retries: 1
  until: result is success
