- name: Upgrade apt packages to their latest version if configured
  apt:
    name: "*"
    state: latest
  when:
    - system_packages_upgrade | bool
    - ansible_facts['os_family'] == "Debian"

- name: Remove apt packages that are no longer required if configured
  apt:
    autoremove: true
  when:
    - system_packages_autoremove | bool
    - ansible_facts['os_family'] == "Debian"

- name: Run Unattended Upgrades directly
  command: unattended-upgrade
  when: unattended_upgrades
