---
- name: Install system packages
  apt:
    name: "{{ system_packages }}"
    update_cache: true
  register: result
  retries: 20
  delay: 5
  until: result is success
  when:
    - ansible_facts['os_family'] == "Debian"

- name: Install python packages
  pip:
    name: "{{ python_packages }}"

- name: Configure Unattended Upgrades
  include_role:
    name: jnv.unattended-upgrades
  when: unattended_upgrades
