---
- name: Lookup GitLab Secrets file if present
  block:
    - name: Check if GitLab Secrets file exists
      stat:
        path: "/etc/gitlab/gitlab-secrets.json"
      register: gitlab_secrets_file

    - name: Lookup GitLab Secrets file if present
      slurp:
        path: "/etc/gitlab/gitlab-secrets.json"
      register: gitlab_secrets_values
      diff: false
      when:
        - gitlab_secrets_file is defined
        - gitlab_secrets_file.stat.exists
        - gitlab_secrets_values != ''
      tags:
        - load
  run_once: true
  tags: load

- name: Copy GitLab Secrets if present
  block:
    - name: test
      copy:
        content: "{{ gitlab_secrets_values | b64decode }}"
        dest: "/etc/gitlab/gitlab-secrets.json"
  tags: copy
