---
- name: Lookup GitLab Secrets file if present
  block:
    - name: Check if GitLab Secrets file exists
      stat:
        path: "/etc/gitlab/gitlab-secrets.json"
      register: gitlab_secrets_file

    - name: Lookup GitLab Secrets file if present
      slurp:
        path: "/etc/gitlab/gitlab-secrets.json"
      register: gitlab_secrets_values
      diff: false
      when:
        - gitlab_secrets_file is defined
        - gitlab_secrets_file.stat.exists
  when:
    - gitlab_secrets_values == ''
  run_once: true
  tags: secrets

- name: Copy GitLab Secrets to file
  block:
    - name: Copy GitLab Secrets to file
      copy:
        content: "{{ gitlab_secrets_values.content | b64decode | from_json | to_nice_json(indent=2) }}\n"
        dest: "/etc/gitlab/gitlab-secrets.json"
  when:
    - omnibus_node
    - gitlab_secrets_values != ''
  tags: secrets
