---
- name: Create /opt/influxdb directory
  file:
    path: /opt/influxdb
    state: directory
  tags:
    - reconfigure

- name: Remove old InfluxDB container
  docker_container:
    name: influxdb
    state: absent
  tags:
    - reconfigure
    - restart

- name: Start InfluxDB Docker
  docker_container:
    name: influxdb
    image: influxdb:1.8-alpine
    pull: true
    restart_policy: always
    state: started
    memory: "{{ influxdb_memory_limit }}m"
    ports: ['8086:8086']
    volumes:
      - /opt/influxdb:/var/lib/influxdb
  tags:
    - reconfigure
    - restart

- name: Wait for InfluxDB to be available
  uri:
    url: 'http://127.0.0.1:8086/health'
  register: result
  until: result.status == 200
  retries: 10
  delay: 3
  tags:
    - reconfigure
    - restart
    - health

- name: Create database in InfluxDB
  shell: |
    docker exec influxdb influx -execute "CREATE DATABASE gpt_results WITH DURATION 90d REPLICATION 1 SHARD DURATION 1d"
    docker exec influxdb influx -execute "CREATE DATABASE sitespeed WITH DURATION 90d REPLICATION 1 SHARD DURATION 1d"
  tags:
    - reconfigure
    - restart
