- name: Copy Secrets - Copy secrets from primary rails to local
  fetch: src=/etc/gitlab/gitlab-secrets.json dest={{ local_tmp }} flat=yes
  tags: primary
  when:
    - ('gitlab_rails_primary' in group_names)
    - ('geo_primary_site' in group_names)

- name: Copy Secrets - Copy secrets from local to secondary nodes
  copy:
    src: "{{ local_tmp }}gitlab-secrets.json"
    dest: /etc/gitlab/gitlab-secrets.json
    owner: root
    group: root
    mode: 0600
  tags: secondary
  when:
    - ('geo_secondary_site' in group_names)
    - omnibus_node

- name: Copy Secrets - Copy secrets from local to secondary nfs
  copy:
    src: "{{ local_tmp }}gitlab-secrets.json"
    dest: "{{ gitlab_nfs_path }}/gitlab-secrets.json"
    owner: root
    group: root
    mode: 0600
  tags: secondary
  when:
    - ('geo_secondary_site' in group_names)
    - ('gitlab_rails_primary' in group_names)

- name: Copy Secrets - Reconfigure GitLab
  command: gitlab-ctl reconfigure
  tags: secondary
  when:
    - ('geo_secondary_site' in group_names)
    - omnibus_node