- name: Copy Secrets - Copy secrets from primary rails to local
  fetch: src=/etc/gitlab/gitlab-secrets.json dest=tmp/ flat=yes
  when:
    - "'gitlab_rails_primary' in group_names"
    - "'geo_primary_site' in group_names"

- name: Copy Secrets - Copy secrets from local to secondary nodes
  copy: src=tmp/gitlab-secrets.json dest=/etc/gitlab/gitlab-secrets.json
  when:
    - "'geo_secondary_site' in group_names"
    - omnibus_node

- name: Copy Secrets - Copy secrets from local to secondary nfs
  copy: src=tmp/gitlab-secrets.json dest={{ gitlab_nfs_path }}/gitlab-secrets.json
  when:
    - "'geo_secondary_site' in group_names"
    - "'gitlab_rails_primary' in group_names"

- name: Copy Secrets - Reconfigure GitLab
  command: gitlab-ctl reconfigure
  when:
    - "'geo_secondary_site' in group_names"
    - omnibus_node