- name: Configure the primary app servers
  import_tasks: primary-app-servers.yml
  tags:
    - primary-app-servers
    - primary

- name: Configure database for the primary site
  import_tasks: primary-database.yml
  tags:
    - primary-database
    - primary
  when:
    - ('postgres' in group_names) or
      ('gitlab_rails' in group_names and geo_primary_site_group_name + '_postgres_primary' not in groups and not postgres_external)
    - (geo_primary_site_group_name in group_names)

- name: Copy Secrets - Copy secrets from primary NFS server to local
  fetch: src={{ gitlab_nfs_path }}/gitlab-secrets.json dest={{ local_tmp }} flat=yes
  tags:
    - copy-secrets
    - secondary
  when:
    - ('gitlab_nfs' in group_names or ('gitlab_nfs' not in groups and 'gitlab_rails_primary' in group_names))
    - (geo_primary_site_group_name in group_names)

- name: Configure Secondary Sites
  include_tasks: secondary-tasks.yml
  tags:
    - copy-secrets
    - secondary-database
    - read-only-replica
    - tracking-database
    - secondary-frontend-app-servers
    - add-site-name
    - secondary-backend-app-servers
    - redeploy-secondary-charts
    - secondary
  loop: "{{ geo_secondary_sites }}"
  loop_control:
    loop_var: secondary_site
