- name: Secondary Geo - Add new config
  blockinfile:
    path: /etc/gitlab/gitlab.rb
    block: "{{ lookup('template', '../templates/secondary-database') }}"
    marker: "# {mark} geo config block - secondary-database"

- name: Read-only Replica - Add new config
  blockinfile:
    path: /etc/gitlab/gitlab.rb
    block: "{{ lookup('template', '../templates/read-only-replica') }}"
    marker: "# {mark} geo config block - read-only-replica"

- name: Read-only Replica - Run gitlab-ctl reconfigure
  command: gitlab-ctl reconfigure