- name: Read-only Replica - Ensure Postgres leader after reconfigure
  import_tasks: set-postgres-leader.yml
  when: install_patroni is defined and install_patroni

- name: Read-only Replica - Add new config
  blockinfile:
    path: /etc/gitlab/gitlab.rb
    block: "{{ lookup('template', '../templates/read-only-replica') }}"
    marker: "# {mark} geo config block - read-only-replica"

- name: Read-only Replica - Run gitlab-ctl reconfigure
  command: gitlab-ctl reconfigure