- name: Secondary Frontend App Servers - Add new config
  template:
    src: templates/secondary-app-servers.rb.j2
    dest: /etc/gitlab/gitlab.geo.secondary-app-servers.rb

- name: Secondary Frontend App Servers - Run gitlab-ctl reconfigure
  command: gitlab-ctl reconfigure

- name: Secondary Frontend App Servers - Run gitlab-ctl restart
  command: gitlab-ctl restart