- name: Set Geo Replication Password - Set replication password using gitlab-ctl
  expect:
    command: gitlab-ctl set-replication-password
    responses:
      (.*)Enter password: "{{ postgres_password }}"
      (.*)Confirm password: "{{ postgres_password }}"
    timeout: 60
  when:
    - postgres_replication_manager != 'patroni'

- name: Set Replication password when using Patroni.
  block:
  - name: Set PostgreSQL leader
    import_tasks: set-postgres-leader.yml

  # Workaround
  # Currently set-replication-password exits with 'There is no PostgreSQL instance enabled in Omnibus, exiting...'
  # when using Patroni. The solution is to set the password directly in the DB until resolved.
  # GitLab Issue: https://gitlab.com/gitlab-org/gitlab/-/issues/271581
  - name: Set Geo Replication Password - Set replication password using gitlab-psql
    command: |
      gitlab-psql -c "ALTER USER gitlab_replicator WITH REPLICATION ENCRYPTED PASSWORD '{{ postgres_password }}';"
  when:
    - postgres_replication_manager == 'patroni'
