- name: Set Geo Replication Password - Set replication password using gitlab-ctl
  expect:
    command: gitlab-ctl set-replication-password
    responses:
      (.*)Enter password: "{{ postgres_password }}"
      (.*)Confirm password: "{{ postgres_password }}"
    timeout: 60