# Workaround
# Currently the gitlab-ctl commands for switchover does not work. Once it is fixed this file
# can be replaced to use a single command.
# gitlab-ctl patroni switchover --candidate "{{ ansible_fqdn }}" --force
# GitLab Issue: https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/5829

- name: "Set Postgres Leader - Get current Patroni leader"
  shell: gitlab-ctl patroni members | grep Leader | cut -d '|' -f 3 | awk '{$1=$1};1'
  register: patroni_leader

# Tells Patroni to switch its leader to match our postgres_primary
# https://patroni.readthedocs.io/en/latest/rest_api.html#switchover-and-failover-endpoints
- name: "Set Postgres Leader - Set postgres_primary to be Patroni leader"
  uri:
    url: http://localhost:8008/switchover
    method: POST
    status_code: 200
    body_format: json
    body:
      leader: "{{ patroni_leader.stdout }}"
      candidate: "{{ ansible_fqdn }}"
  register: result
  until: result is not failed
  retries: 11
  delay: 5
  when: patroni_leader.stdout != ansible_fqdn