- name: Tracking Database - Add new config
  template:
    src: templates/tracking-database.rb.j2
    dest: /etc/gitlab/gitlab.geo.tracking-database.rb

- name: Tracking Database - Run gitlab-ctl reconfigure
  command: gitlab-ctl reconfigure

- name: Tracking Database - Run gitlab-ctl restart for updates to take effect
  command: gitlab-ctl restart
