all:
  vars:
    prefix: "omnibus-3k"
    project_name: "gitlab-qa-distribution"
    ansible_user: "sa_117401977288730813591"
    ansible_ssh_private_key_file: "../keys/distribution/gitlab-qa-distribution-ssh"
    gitlab_license_file: "../keys/distribution/Gitlab.gitlab-license"
    external_url: "http://104.196.38.24"
    install_patroni: true
