plugin: gcp_compute
projects:
  - gitlab-qa-10k-cd77c7
filters:
keyed_groups:
  - key: labels.gitlab_node_type
    separator: ''
  - key: labels.gitlab_node_level
    separator: ''
scopes:
  - https://www.googleapis.com/auth/compute
service_account_file: ../secrets/serviceaccount-10k.json
auth_kind: serviceaccount
