---
- name: Create the /etc/gitlab/gitlab.rb file
  template:
    src: templates/postgres_ha.gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
  tags: gitlab_template

- name: Reconfigure GitLab
  shell: gitlab-ctl reconfigure
  tags: reconfigure

- name: Check secondary standby status
  shell: (gitlab-ctl repmgr cluster show 2>/dev/null | grep -E 'standby | {{ ansible_hostname }}') || echo ""
  register: postgres_secondary_standby_status
  tags: postgres_secondary_standby
  when: 
    - "'postgres_secondary' in group_names"

- name: Enable secondary standby
  shell: "gitlab-ctl repmgr standby setup {{ postgres_primary_ip }} -w"
  tags: postgres_secondary_standby
  when: 
    - "'postgres_secondary' in group_names"
    - postgres_secondary_standby_status.stdout == ''

- name: Create skip-auto-reconfigure file
  file:
    path: /etc/gitlab/skip-auto-reconfigure
    state: touch
    mode: u=rw,g=r,o=r