- name: Primary App Servers - Add new config
  template:
    src: templates/primary-app-servers.rb.j2
    dest: /etc/gitlab/gitlab.geo.primary-app-servers.rb

- name: Primary App Servers - Run gitlab-ctl reconfigure
  command: gitlab-ctl reconfigure

- name: Primary App Servers - Set geo primary node
  command: gitlab-ctl set-geo-primary-node
  when: ('gitlab_rails_primary' in group_names)
