- name: Tracking Database - Ensure Postgres leader after reconfigure
  import_tasks: set-postgres-leader.yml
  when: postgres_replication_manager == 'patroni'

- name: Tracking Database - Add new config
  template:
    src: templates/tracking-database.rb.j2
    dest: /etc/gitlab/gitlab.geo.tracking-database.rb

- name: Tracking Database - Run gitlab-ctl reconfigure
  command: gitlab-ctl reconfigure

- name: Tracking Database - Run gitlab-ctl restart for updates to take effect
  command: gitlab-ctl restart

# Workaround
# The first reconfigure enables the Geo PostgreSQL database but doesn't set the password for the gitlab_geo user.
# The password is only being set as part of the second reconfigure.
# GitLab Issue: https://gitlab.com/gitlab-org/gitlab/-/issues/276216
# GET Issue to remove: https://gitlab.com/gitlab-org/quality/gitlab-environment-toolkit/-/issues/37
- name: Tracking Database - Run gitlab-ctl reconfigure
  command: gitlab-ctl reconfigure
