consul_internal_ips: "{{ groups['consul'] | map('extract', hostvars, ['networkInterfaces']) |  map('first') | map(attribute='networkIP') | list }}"
consul_password: '0a6da13ae1754357b71ba1ac6c6caa6b'
postgres_password: '37aca09f2f8ff04f27bdb2ed159ec81f'
pgbouncer_password: '9fdf957895675ef0741f66811c8fa958'
redis_password: 'rae5ceiH3sheeGohz2la'
redis_primary_ip: "{{ groups['redis_primary'] | map('extract', hostvars, ['networkInterfaces']) |  map('first') | map(attribute='networkIP') | join('') }}"
pgbouncer_ip: "{{ groups['pgbouncer'] | map('extract', hostvars, ['networkInterfaces']) |  map('first') | map(attribute='networkIP') | join('') }}"
gitaly_ip: "{{ groups['gitaly'] | map('extract', hostvars, ['networkInterfaces']) |  map('first') | map(attribute='networkIP') | join('') }}"
# global_ip: "{{ groups['gitlab_rails_primary'] | map('extract', hostvars, ['metadata', 'items']) | sum(start=[]) | selectattr('key', 'equalto', 'global_ip') | map(attribute='value')| join('') }}"
gitlab_rails_ips: "{{ (groups['gitlab_rails_primary'] + groups['gitlab_rails_secondary']) | map('extract', hostvars, ['networkInterfaces']) |  map('first') | map(attribute='networkIP') | list }}"
global_ip: "{{ groups['haproxy'] | map('extract', hostvars, ['networkInterfaces']) |  sum(start=[]) | map(attribute='accessConfigs') | sum(start=[]) | map(attribute='natIP') | join('') }}"
external_url: "http://{{ global_ip }}"