# Ansible / General
install_gitlab: true
gitlab_secrets_storage: "{{ prefix }}-secrets-storage"
gitlab_object_storage: "{{ prefix }}-object-storage"

# Consul
consul_int_ips: "{{ groups['consul'] | map('extract', hostvars, ['networkInterfaces']) |  map('first') | map(attribute='networkIP') | list }}"
consul_password: '0a6da13ae1754357b71ba1ac6c6caa6b'

# HAProxy / Network
haproxy_internal_int_ip: "{{ groups['haproxy_internal'] | map('extract', hostvars, ['networkInterfaces']) |  map('first') | map(attribute='networkIP') | join('') }}"
haproxy_external_int_ip: "{{ groups['haproxy_external'] | map('extract', hostvars, ['networkInterfaces']) |  map('first') | map(attribute='networkIP') | join('') }}"
haproxy_external_ext_ip: "{{ groups['haproxy_external'] | map('extract', hostvars, ['networkInterfaces']) |  map('first') | map(attribute='accessConfigs') | map('first') | map(attribute='natIP') | join('') }}"
global_ip: "{{ haproxy_external_ext_ip }}"

# Gitaly
gitaly_primary_int_ip: "{{ groups['gitaly_primary'] | map('extract', hostvars, ['networkInterfaces']) |  map('first') | map(attribute='networkIP') | join('') }}"
gitaly_secondary_int_ips: "{{ groups['gitaly_secondary'] | map('extract', hostvars, ['networkInterfaces']) |  map('first') | map(attribute='networkIP') | list }}"
gitaly_token: 'abc123secret'

# GitLab NFS
gitlab_nfs_int_ip: "{{ groups['gitlab_nfs'] | map('extract', hostvars, ['networkInterfaces']) |  map('first') | map(attribute='networkIP') | join('') }}"
gitlab_nfs_path: "/mnt/gitlab-nfs"
gitlab_nfs_export_cidr: "{{ (ansible_default_ipv4.address + '/16') | ipaddr('network/prefix') }}"

# GitLab Rails
gitlab_rails_int_ips: "{{ (groups['gitlab_rails_primary'] + groups['gitlab_rails_secondary']) | map('extract', hostvars, ['networkInterfaces']) |  map('first') | map(attribute='networkIP') | list }}"

# GitLab Monitor
monitor_int_ip: "{{ groups['monitor'] | map('extract', hostvars, ['networkInterfaces']) |  map('first') | map(attribute='networkIP') | join('') }}"

# GitLab Postgres / PGBouncer
postgres_password: '37aca09f2f8ff04f27bdb2ed159ec81f'
pgbouncer_password: '9fdf957895675ef0741f66811c8fa958'
pgbouncer_int_ips: "{{ groups['pgbouncer'] | map('extract', hostvars, ['networkInterfaces']) |  map('first') | map(attribute='networkIP') | list }}"

# GitLab Redis
redis_password: 'rae5ceiH3sheeGohz2la'
redis_cache_primary_int_ip: "{{ groups['redis_cache_primary'] | map('extract', hostvars, ['networkInterfaces']) |  map('first') | map(attribute='networkIP') | join('') }}"
redis_cache_int_ips: "{{ groups['redis_cache'] | map('extract', hostvars, ['networkInterfaces']) |  map('first') | map(attribute='networkIP') | list }}"
redis_persistent_primary_int_ip: "{{ groups['redis_persistent_primary'] | map('extract', hostvars, ['networkInterfaces']) |  map('first') | map(attribute='networkIP') | join('') }}"
redis_persistent_int_ips: "{{ groups['redis_persistent'] | map('extract', hostvars, ['networkInterfaces']) |  map('first') | map(attribute='networkIP') | list }}"

# Jaeger Distributed Tracing
jaeger: "{{ 'jaeger' in groups }}"
jaeger_int_ip: "{{ (groups['jaeger'] | map('extract', hostvars, ['networkInterfaces']) |  map('first') | map(attribute='networkIP') | join('')) if jaeger else '' }}"
