gitaly_number: "{{ ansible_hostname | regex_search('gitaly-(\\d+)', '\\1') | first }}"
gitaly_ruby_num_workers: "{{ (ansible_processor_vcpus * 0.2) | round | int }}"

gitaly_cluster_storage_path: "/var/opt/gitlab/git-data"
gitaly_sharded_storage_path: "/mnt/gitlab"
