gitlab_rails_puma_workers: "{% if ansible_processor_vcpus is defined %}{{ (ansible_processor_vcpus * 0.9) | round | int }}{% else %}29{% endif %}"
gitlab_rails_puma_threads: 4

serviceaccount_filename: "serviceaccount.json"
serviceaccount_path: "/etc/gitlab/{{ serviceaccount_filename }}"