---
- name: Create /etc/gitlab/gitlab.rb
  template:
    src: templates/gitaly.gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
  tags: 
    - gitlab_template
    - reconfigure

- name: Download secrets file
  shell: "gsutil cp gs://{{ gitlab_conf_storage }}/gitlab-secrets.json /etc/gitlab/gitlab-secrets.json 2>/dev/null || true"
  tags: secrets

- name: Reconfigure GitLab
  shell: gitlab-ctl reconfigure
  tags: reconfigure

- name: Restart Gitaly
  command: gitlab-ctl restart
  tags:
    - reconfigure
    - restart

- name: Upload secrets file if missing
  shell: "gsutil cp -n /etc/gitlab/gitlab-secrets.json gs://{{ gitlab_conf_storage }}"
  tags: secrets
  run_once: true

- name: Create Default Gitaly directory
  file:
    path: "/mnt/gitlab/default/repositories"
    state: directory
    mode: '0755'
    owner: git
    group: git
  when: "'gitaly_primary' in group_names"

- name: Create Additional Gitaly directories
  file:
    path: "/mnt/gitlab/storage{{ gitaly_number }}/repositories"
    state: directory
    mode: '0755'
    owner: git
    group: git

- name: Create skip-auto-reconfigure file
  file:
    path: /etc/gitlab/skip-auto-reconfigure
    state: touch
    mode: u=rw,g=r,o=r