---
- name: Setup GitLab config file
  template:
    src: templates/gitaly.gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
  register: result
  retries: 3
  until: result is success
  tags: reconfigure

- name: Download secrets file
  shell: "gsutil cp gs://{{ gitlab_secrets_storage }}/gitlab-secrets.json /etc/gitlab/gitlab-secrets.json 2>/dev/null || true"
  tags: secrets
  
- name: Reconfigure Gitaly
  shell: gitlab-ctl reconfigure
  tags: reconfigure

- name: Create Default Gitaly directory
  file:
    path: "/mnt/gitlab/default/repositories"
    state: directory
    mode: '2770'
    owner: git
    group: git
  when: "'gitaly_primary' in group_names"
  tags: reconfigure

- name: Create Additional Gitaly directories
  file:
    path: "/mnt/gitlab/storage{{ gitaly_number }}/repositories"
    state: directory
    mode: '2770'
    owner: git
    group: git
  tags: reconfigure

- name: Restart Gitaly
  command: gitlab-ctl restart
  register: result
  retries: 2
  until: result is success
  tags:
    - reconfigure
    - restart

- name: Upload secrets file if missing
  shell: "gsutil cp -n /etc/gitlab/gitlab-secrets.json gs://{{ gitlab_secrets_storage }}"
  tags: secrets
  run_once: true

- name: Create skip-auto-reconfigure file
  file:
    path: /etc/gitlab/skip-auto-reconfigure
    state: touch
    mode: u=rw,g=r,o=r