- name: Generate OAuth Token if not present
  include_tasks: oauth-token.yml
  when: gitlab_oauth_token is not defined
  tags: oauth

- name: Configure Deletion Adjourned period
  uri:
    url: '{{ external_url_sanitised }}/api/v4/application/settings'
    method: PUT
    headers:
      Authorization: 'Bearer {{ gitlab_oauth_token }}'
    body:
      deletion_adjourned_period: 0
    status_code: 200, 201
    body_format: json

- name: Disable Limits
  uri:
    url: '{{ external_url_sanitised }}/api/v4/application/settings'
    method: PUT
    headers:
      Authorization: 'Bearer {{ gitlab_oauth_token }}'
    body:
      issues_create_limit: 0
      raw_blob_request_limit: 0
      max_import_size: 0
    status_code: 200, 201
    body_format: json

- name: Disable User Signup
  uri:
    url: '{{ external_url_sanitised }}/api/v4/application/settings'
    method: PUT
    headers:
      Authorization: 'Bearer {{ gitlab_oauth_token }}'
    body:
      signup_enabled: false
    status_code: 200, 201
    body_format: json
