- name: Configure Ultimate License
  import_tasks: license.yml
  when:
    - gitlab_license_file is defined
    - gitlab_license_plan is not defined
  tags: license

- name: Configure any required settings via API
  import_tasks: configure.yml
  tags: reconfigure

- name: Configure Advanced Search with Elasticsearch
  import_tasks: elasticsearch.yml
  when: "'elastic' in groups"
  tags: elasticsearch
