- name: Wait for GitLab to be available
  uri:
    url: '{{ external_url }}/-/readiness'
    timeout: 60
  register: result
  until: result.status == 200
  retries: 20
  delay: 5
  tags: healthcheck

- name: GitLab Root Password check
  fail:
    msg: "GitLab Root Password is empty. Post Configure steps will be skipped. Refer to docs for more info - https://gitlab.com/gitlab-org/quality/gitlab-environment-toolkit/-/blob/master/docs/prep_toolkit.md#gitlab-initial-root-password "
  ignore_errors: true
  when: gitlab_root_password == ''
  tags: config-check

- name: Generate Access Token
  shell: |
    gitlab-rails runner "
      existingToken = PersonalAccessToken.find_by_token('{{ access_token_key }}')

      if existingToken == nil
        token=User.find_by_username('{{ access_token_user }}').
                   personal_access_tokens.create(
                     scopes: {{ access_token_scopes }},
                     name: 'GitLab Environment Toolkit API Token'
                   )
        token.set_token('{{ access_token_key }}')
        token.save!
      end
    "
  tags:
    - access_token
    - license
    - reconfigure
    - elasticsearch

- name: Do GitLab post configuration
  block:
    - name: Configure Ultimate License
      import_tasks: license.yml
      when:
        - gitlab_license_file is defined
        - gitlab_license_plan is not defined
      tags: license

    - name: Configure any required settings via API
      import_tasks: configure.yml
      tags: reconfigure

    - name: Configure Advanced Search with Elasticsearch
      import_tasks: elasticsearch.yml
      when:
        - "'elastic' in groups"
        - gitlab_license_file is defined
        - gitlab_license_plan is defined
      tags: elasticsearch
  when: gitlab_root_password != ''

- name: Remove Access Token
  block:
    - name: Revoke Access Token
      shell: |
        gitlab-rails runner "PersonalAccessToken.find_by_token('{{ access_token_key }}').revoke!"

    - name: Remove saved Access Token
      file: path=tmp/access-token state=absent
      delegate_to: localhost
      become: false
  tags:
    - access_token
    - license
    - reconfigure
    - elasticsearch
