---
- name: Setup GitLab config file
  template:
    src: templates/praefect_postgres.gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
  tags: reconfigure

- name: Check if custom config exists
  stat:
    path: "{{ praefect_postgres_custom_config_file }}"
  delegate_to: localhost
  become: false
  tags: reconfigure
  register: praefect_postgres_custom_config_file_path

- name: Copy custom GitLab config file
  copy:
    src: "{{ praefect_postgres_custom_config_file }}"
    dest: "/etc/gitlab/gitlab.praefect_postgres.custom.rb"
    mode: 0644
  tags: reconfigure
  when: praefect_postgres_custom_config_file_path.stat.exists

- name: Reconfigure Praefect PostgreSQL
  shell: gitlab-ctl reconfigure
  tags: reconfigure

- name: Restart Praefect PostgreSQL
  command: gitlab-ctl restart
  register: result
  retries: 2
  until: result is success
  tags:
    - reconfigure
    - restart

- name: Create skip-auto-reconfigure file
  file:
    path: /etc/gitlab/skip-auto-reconfigure
    state: touch
    mode: u=rw,g=r,o=r
