---
- hosts: localhost

  tasks:
  - name: Uninstall GitLab Charts
    kubernetes.core.helm:
      release_name: gitlab
      release_namespace: "{{ gitlab_charts_release_namespace }}"
      state: absent
      wait: true
    when:
      - cloud_native_hybrid_environment
    tags: gitlab_charts
