all:
  vars:
    cloud_provider: "gcp"
    prefix: "gitlab-qa-25k"
    project_name: "gitlab-qa-25k-bc38fe"
    ansible_user: "sa_109616956154772805294"
    ansible_ssh_private_key_file: "../keys/performance/gitlab-qa-ssh"
    gitlab_license_file: "../keys/performance/Gitlab.gitlab-license"
    external_url: "http://25k.testbed.gitlab.net"
