---
- hosts: all:!ungrouped
  become: true

  roles:
    - common_vars

  tasks:
    block:
      - name: Uninstall GitLab Omnibus
        include_role:
          name: common
          tasks_from: uninstall
      - name: Uninstall GitLab Version Exporter
        include_role:
          name: gitlab_version_exporter
          tasks_from: uninstall
    when: omnibus_node

- hosts: localhost

  roles:
    - common_vars

  tasks:
    - name: Uninstall GitLab Charts
      include_role:
        name: gitlab-charts
        tasks_from: uninstall
      when: cloud_native_hybrid_environment
