- name: Copy Secrets from primary site to all secondaries
  block:
    - name: Copy secrets from bucket site to secondary bucket
      shell: "gsutil cp /etc/gitlab/gitlab-secrets.json gs://geo-3k-secondary-secrets-storage/gitlab-secrets.json 2>/dev/null || true"
      when: 
        - "'gitlab_rails_primary' in group_names"
        - "'geo_primary' in group_names"

    - name: Download new secrets file
      shell: "gsutil cp gs://geo-3k-secondary-secrets-storage/gitlab-secrets.json /etc/gitlab/gitlab-secrets.json 2>/dev/null || true"
      when: "'geo_secondary' in group_names"

    - name: Reconfigure GitLab
      shell: gitlab-ctl reconfigure
      tags: reconfigure
      when: 
        - "'geo-secondary' in group_names"
        - omnibus_node
  tags: secrets

- name: Set GitLab primary geo node
  block:
    - name: Set geo_node_name for primary rails
      lineinfile:
        path: /etc/gitlab/gitlab.rb
        line: gitlab_rails['geo_node_name'] = '{{ inventory_hostname }}'
            
    - name: Run gitlab-ctl set-geo-primary-node
      shell: gitlab-ctl set-geo-primary-node
  tags: set-primary-geo
  when:
    - "'gitlab_rails_primary' in group_names"
    - "'geo_primary' in group_names"