- name: Copy secrets from primary site to secondary
  shell: "gsutil cp /etc/gitlab/gitlab-secrets.json gs://geo-3k-secondary-secrets-storage/gitlab-secrets.json 2>/dev/null || true"
  tags: secrets
  when: 
    - "'gitlab_rails_primary' in group_names"
    - "'geo-primary' in group_names"

- name: Download new secrets file
  shell: "gsutil cp gs://geo-3k-secondary-secrets-storage/gitlab-secrets.json /etc/gitlab/gitlab-secrets.json 2>/dev/null || true"
  tags: secrets
  when: "'geo-secondary' in group_names"

- name: Reconfigure GitLab
  shell: gitlab-ctl reconfigure
  tags:
    - secrets
    - reconfigure
  when: 
    - "'geo-secondary' in group_names"
    - omnibus_node

# - name: Set up the database replication on primary # https://docs.gitlab.com/ee/administration/geo/replication/database.html

# - name: Configure GitLab to set the primary and secondary nodes # https://docs.gitlab.com/ee/administration/geo/replication/configuration.html