- name: Copy Secrets - Copy secrets from bucket site to secondary bucket
  shell: "gsutil cp /etc/gitlab/gitlab-secrets.json gs://geo-3k-secondary-secrets-storage/gitlab-secrets.json 2>/dev/null || true"
  when: 
    - "'gitlab_rails_primary' in group_names"
    - "'geo_primary' in group_names"

- name: Copy Secrets - Download new secrets file
  shell: "gsutil cp gs://geo-3k-secondary-secrets-storage/gitlab-secrets.json /etc/gitlab/gitlab-secrets.json 2>/dev/null || true"
  when: "'geo_secondary' in group_names"

- name: Copy Secrets - Reconfigure GitLab
  shell: gitlab-ctl reconfigure
  tags: reconfigure
  when: 
    - "'geo-secondary' in group_names"
    - omnibus_node
