- name: Copy Secrets - Copy secrets from bucket site to secondary bucket
  fetch: src=~/etc/gitlab/gitlab-secrets.json dest=tmp/ flat=yes
  when: 
    - "'gitlab_rails_primary' in group_names"
    - "'geo_primary' in group_names"

- name: Copy Secrets - Download new secrets file
  copy: src=tmp/gitlab-secrets.json dest=/etc/gitlab/gitlab-secrets.json
  when: "'geo_secondary' in group_names"

- name: Copy Secrets - Reconfigure GitLab
  shell: gitlab-ctl reconfigure
  tags: reconfigure
  when: 
    - "'geo-secondary' in group_names"
    - omnibus_node
