- name: Copy Secrets - Copy secrets from primary rails to local
  fetch: src=/etc/gitlab/gitlab-secrets.json dest=tmp/ flat=yes
  when: 
    - "'gitlab_rails_primary' in group_names"
    - "'geo_primary' in group_names"

- name: Copy Secrets - Copy secrets from local to secondary nodes
  copy: src=tmp/gitlab-secrets.json dest=/etc/gitlab/gitlab-secrets.json
  when: 
    - "'geo_secondary' in group_names"
    - omnibus_node

- name: Copy Secrets - Reconfigure GitLab
  shell: gitlab-ctl reconfigure
  when: 
    - "'geo-secondary' in group_names"
    - omnibus_node