- name: Set replication password
  expect: 
    command: gitlab-ctl set-replication-password
    responses:
      (.*)Enter password: "{{ postgres_password }}"
      (.*)Confirm password: "{{ postgres_password }}"
    creates: skip-set-replication-password
    timeout: 60
