- name: Configure the primary frontend servers
  import_tasks: primary-frontend.yml
  tags: 
    - primary-frontend
    - primary
  when:
    - "'gitlab_rails' in group_names or 'sidekiq' in group_names"
    - "'geo_primary' in group_names"

- name: Get PostgreSQL leader
  import_tasks: postgres-leader.yml
  tags: 
    - postgres-leader
    - geo-database-replication
    - primary-database
    - secondary-database
  when:
    - "'postgres_primary' in group_names"
    - "'geo_primary' in group_names"

- name: Configure Geo database replication
  import_tasks: geo-database-replication.yml
  tags: 
    - geo-database-replication
    - primary
  when: postgres_leader_hostname == inventory_hostname

- name: Configure the primary database
  import_tasks: primary-database.yml
  tags: 
    - primary-database
    - primary
  when: postgres_leader_hostname == inventory_hostname

- name: copy secrets
  import_tasks: copy-secrets.yml
  tags: copy-secrets

- name: Configure the secondary database
  import_tasks: secondary-database.yml
  tags: 
    - secondary-database
    - secondary
  when: 
    - "'postgres_primary' in group_names"
    - "'geo_secondary' in group_names"
  
- name: Configure the main read-only replica PostgreSQL database on the secondary node
  import_tasks: read-only-replica.yml
  tags: 
    - read-only-replica
    - secondary
  when: 
    - "'postgres_primary' in group_names"
    - "'geo_secondary' in group_names"
  
- name: Configure the tracking database on the secondary node
  import_tasks: tracking-db.yml
  tags: 
    - tracking-db
    - secondary
  when:
    - "'postgres_primary' in group_names"
    - "'geo_secondary' in group_names"

- name: Configure the frontend application servers on the secondary node
  import_tasks: secondary-app-servers.yml
  tags: 
    - secondary-app-servers
    - secondary
  when:
    - "'gitlab_rails' in group_names"
    - "'geo_secondary' in group_names"

- name: Add secondary Geo site to tracking database
  import_tasks: add-site-name.yml
  tags: 
    - add-site-name
    - secondary
  when:
    - "'gitlab_rails_primary' in group_names"
    - "'geo_primary' in group_names"

- name: Configure backend application servers
  import_tasks: secondary-backend-servers.yml
  tags: 
    - secondary-backend-servers
    - secondary
  when:
    - "'sidekiq' in group_names"
    - "'geo_secondary' in group_names"
