- name: Copy Secrets from primary site to all secondaries
  import_tasks: secrets.yml
  tags: copy-secrets

- name: Configure the primary frontend servers
  import_tasks: primary-frontend.yml
  tags: set-primary-geo
  when:
    - "'gitlab_rails' in group_names or 'sidekiq' in group_names"
    - "'geo_primary' in group_names"

- name: Configure the primary database
  import_tasks: primary-database.yml
  tags: set-primary-db
  when: "'postgres_primary' in group_names"
  
- name: Configure the main read-only replica PostgreSQL database on the secondary node
  import_tasks: read-only-replica.yml
  tags: replica-db
  when: 
    - "'postgres_primary' in group_names"
    - "'geo_secondary' in group_names"
  
- name: Configure the tracking database on the secondary node
  import_tasks: tracking-db.yml
  tags: tracking-db
  when:
    - "'postgres_primary' in group_names"
    - "'geo_secondary' in group_names"

- name: Configure the frontend application servers on the secondary node
  import_tasks: secondary-app-servers.yml
  tags: secondary-app-servers
  when:
    - "'gitlab_rails' in group_names"
    - "'geo_secondary' in group_names"