- name: Configure the primary frontend servers
  import_tasks: primary-frontend.yml
  tags: primary-frontend
  when:
    - "'gitlab_rails' in group_names or 'sidekiq' in group_names"
    - "'geo_primary' in group_names"

- name: Get PostgreSQL leader
  import_tasks: postgres-leader.yml
  tags: 
    - postgres-leader
    - geo-database-replication
    - primary-database
  when:
    - "'postgres_primary' in group_names"
    - "'geo_primary' in group_names" 

- name: Configure Geo database replication
  import_tasks: geo-database-replication.yml
  tags: geo-database-replication
  delegate_to: "{{ postgres_leader }}"
  when: postgres_leader is defined

- name: Configure the primary database
  import_tasks: primary-database.yml
  tags: primary-database
  delegate_to: "{{ postgres_leader }}"
  when: postgres_leader is defined
  
- name: Configure the main read-only replica PostgreSQL database on the secondary node
  import_tasks: read-only-replica.yml
  tags: read-only-replica
  when: 
    - "'postgres_primary' in group_names"
    - "'geo_secondary' in group_names"
  
- name: Configure the tracking database on the secondary node
  import_tasks: tracking-db.yml
  tags: tracking-db
  when:
    - "'postgres_primary' in group_names"
    - "'geo_secondary' in group_names"

- name: Configure the frontend application servers on the secondary node
  import_tasks: secondary-app-servers.yml
  tags: secondary-app-servers
  when:
    - "'gitlab_rails' in group_names"
    - "'geo_secondary' in group_names"