- name: Get Postgres leader info when using patroni
  block:
    - name: Get PostgreSQL leader hostname
      shell: |
        gitlab-ctl patroni members | grep Leader | cut -d '|' -f 3 | cut -d '.' -f 1 | awk '{$1=$1};1'
      register: postgres_leader_hostname

    - name: Get PostgreSQ leader ip
      shell: |
        gitlab-ctl patroni members | grep Leader | cut -d '|' -f 4 | awk '{$1=$1};1'
      register: postgres_leader_ip

    - name: Store postgres leader hostname when using patroni
      set_fact: "postgres_leader_hostname={{ postgres_leader_hostname.stdout }}"
      delegate_to: "{{ postgres_leader_hostname.stdout }}"

    - name: Store postgres leader ip when using patroni
      set_fact: "postgres_leader_ip={{ postgres_leader_ip.stdout }}"
      delegate_to: "{{ geo_secondary_postgres_int_ip }}"
  when:
    - install_patroni is defined and install_patroni

- name: Get Postgres leader info when using repmgr
  block:
    - name: Store Postgres leader hostname when using repmgr
      set_fact: postgres_leader_hostname={{ inventory_hostname }}

    - name: Store Postgres leader ip when using repmgr
      set_fact: postgres_leader_ip={{ geo_primary_postgres_int_ip }}
  when:
    - install_patroni is not defined or install_patroni == false

- debug:
    msg: "Postgres Leader Info\n  Hostname: {{ postgres_leader_hostname }}\n  IP: {{ postgres_leader_ip }}"
  tags: debug 