- name: Secondary Backend Servers - Update gitlab.rb settings for sidekiq nodes
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    line:  roles ['geo_secondary_role']    

- name: Secondary Backend Servers - Add new config
  blockinfile:
    path: /etc/gitlab/gitlab.rb
    block: |
      gitlab_rails['geo_node_name'] = 'Secondary Site'

      geo_secondary['db_host'] = '{{ geo_secondary_postgres_int_ip }}'
      geo_secondary['db_password'] = '{{ postgres_password }}'
      geo_postgresql['enable'] = false

      geo_logcursor['enable'] = true
    marker: "# {mark} secondary-app-servers ANSIBLE MANAGED BLOCK"

- name: Secondary Backend Servers - Run gitlab-ctl reconfigure
  shell: gitlab-ctl reconfigure

- name: Secondary Backend Servers - Run gitlab-ctl restart
  shell: gitlab-ctl restart
  