- name: Copy psql certificate
  copy: src=tmp/server.crt dest=/tmp/

- name: Install certificate
  shell: |
    install -D \
            -o gitlab-psql \
            -g gitlab-psql \
            -m 0400 \
            -T /tmp/server.crt ~gitlab-psql/.postgresql/root.crt

- name: Update sql_user_password
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regex: "postgresql\\['sql_user_password']"
    line: "postgresql['sql_user_password'] = '{{ (postgres_password + 'gitlab') | md5 }}'"

- name: Run gitlab-ctl reconfigure
  shell: gitlab-ctl reconfigure
  
- name: Restart Postgres
  command: gitlab-ctl restart postgres

- name: Replicate geo database
  expect: 
    command: gitlab-ctl replicate-geo-database --slot-name={{ inventory_hostname | regex_replace("-", "_") }} --host={{ geo_primary_postgres_int_ip }} --force
    responses:
      (.*)Confirmation: "replicate"
      (.*)Enter the password for gitlab_replicator@(.*): "{{ postgres_password }}"
    timeout: null