- name: "Set Postgres Leader - Get current Patroni leader"
  shell: gitlab-ctl patroni members | grep Leader | grep {{ ansible_fqdn }}
  register: patroni_leader
  ignore_errors: true

- name: "Set Postgres Leader - Set postgres_primary to be Patroni leader"
  command: gitlab-ctl patroni switchover --candidate "{{ ansible_fqdn }}"
  register: result
  until: result is not failed
  retries: 11
  delay: 5
  when: patroni_leader.failed
