- name: Secondary Geo - Add new config
  blockinfile:
    path: /etc/gitlab/gitlab.rb
    block: "{{ lookup('template', '../templates/secondary-geo') }}"
    marker: "# {mark} geo config block - secondary-geo"

- name: Tracking Database - Add new config
  blockinfile:
    path: /etc/gitlab/gitlab.rb
    block: "{{ lookup('template', '../templates/tracking-database') }}"
    marker: "# {mark} geo config block - tracking-database"

- name: Tracking DB - Run gitlab-ctl reconfigure
  shell: gitlab-ctl reconfigure

- name: Tracking DB - Run gitlab-ctl restart for updates to take effect
  shell: gitlab-ctl restart