- name: Install NFS Server on a single server
  run_once: true
  block:
    - name: Install NFS Server
      apt:
        name: ['nfs-kernel-server']
        update_cache: true

    - name: Disable NFS Server Delegation
      shell: |
        echo 0 > /proc/sys/fs/leases-enable
        sysctl -w fs.leases-enable=0

    - name: Create GitLab NFS directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0777'
      with_items:
        - "{{ gitlab_nfs_path }}"

    - name: Create /etc/exports
      template:
        src: templates/exports.j2
        dest: /etc/exports

    - name: restart nfs server
      service:
        name: nfs-kernel-server
        state: restarted

    - name: Get NFS IP
      set_fact:
        gitlab_nfs_int_ip: "{{ ansible_default_ipv4.address }}"

    - name: Install cloudalchemy.node_exporter if using a dedicated NFS server
      include_role: cloudalchemy.node_exporter
      when: ('gitlab_nfs' in group_names)
