plugin: gcp_compute
projects:
  - group-geo-f9c951
filters:
  - labels.gitlab_node_prefix = jsl-3k-geo-primary
keyed_groups:
  - key: labels.gitlab_node_type
    separator: ''
  - key: labels.gitlab_node_level
    separator: ''
  - key: labels.gitlab_node_prefix
    separator: ''
scopes:
  - https://www.googleapis.com/auth/compute
service_account_file: ../secrets/serviceaccount-minimal-ha.json
auth_kind: serviceaccount
hostnames:
  # List host by name instead of the default public ip
  - name
compose:
  # Set an inventory parameter to use the Public IP address to connect to the host
  # For Private ip use "networkInterfaces[0].networkIP"
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
