---
- hosts: all:!ungrouped
  roles:
    - common
  become: true

# Common
- import_playbook: haproxy.yml
- import_playbook: gitlab-nfs.yml

# Single Node
- import_playbook: gitlab.yml

# Multi Node
- import_playbook: consul.yml
- import_playbook: postgres.yml
- import_playbook: pgbouncer.yml
- import_playbook: redis.yml
- import_playbook: gitaly.yml
- import_playbook: sidekiq.yml
- import_playbook: gitlab-rails.yml

# Common
- import_playbook: monitor.yml