---
- hosts: all
  roles:
    - common
  become: true
  tasks:
    - set_fact: running_all="true"

- import_playbook: haproxy.yml
- import_playbook: gitlab-nfs.yml
- import_playbook: consul.yml
- import_playbook: postgres.yml
- import_playbook: pgbouncer.yml
- import_playbook: redis.yml
- import_playbook: gitaly.yml
- import_playbook: sidekiq.yml
- import_playbook: gitlab-rails.yml
# - import_playbook: gitlab-geo.yml  # FIXME: needs to run with both primary & secondary inventory
- import_playbook: monitor.yml
