---
- hosts: all:!ungrouped
  become: true

  tasks:
  - debug:
      msg: "{{ error }}"

  - name: Search for error string
    shell: "ack -s '{{ error }}' /var/log/gitlab || true"
    register: output
    ignore_errors: true

  - debug:
      msg: "{{ output.stdout_lines }}"
