---
- hosts: gitlab_rails_primary
  vars:
    consul_ips: "{{ groups['consul'] | map('extract', hostvars, ['networkInterfaces']) |  map('first') | map(attribute='networkIP') | list }}"
    ip_test: "{{ ansible_default_ipv4.address }}/16"

  tasks:
  - debug:
      msg: "{{ groups['postgres_secondary'] | map('extract', hostvars, ['networkInterfaces']) |  map('first') | map(attribute='networkIP') | join(',') }}"

  - debug:
      msg: "{{ ((groups['postgres_primary'] + groups['postgres_secondary']) | length) + 1 }}"

  - debug:
      msg: "{{ ansible_default_ipv4 | ipsubnet(16) }}"

  - debug:
      msg: "{{ gitlab_conf_storage }}"