---
- hosts: redis_*
  vars:
    consul_ips: "{{ groups['consul'] | map('extract', hostvars, ['networkInterfaces']) |  map('first') | map(attribute='networkIP') | list }}"
    ip_test: "{{ ansible_default_ipv4.address }}/16"

  tasks:
  - debug:
      msg: "{{ groups['postgres_secondary'] | map('extract', hostvars, ['networkInterfaces']) |  map('first') | map(attribute='networkIP') | join(',') }}"

  - debug:
      msg: "{{ ((groups['postgres_primary'] + groups['postgres_secondary']) | length) + 1 }}"

  - debug:
      # msg: "{{ zip(groups['gitaly'] | map('regex_search', 'gitaly-\\d+') | list, 1) }}"
      msg: "{{ ansible_memory_mb.real.total }} - {{ ((ansible_memory_mb.real.total | int) * 0.9) | int }}mb"
