---
- hosts: postgres_secondary
  vars:
    consul_ips: "{{ groups['consul'] | map('extract', hostvars, ['networkInterfaces']) |  map('first') | map(attribute='networkIP') | list }}"

  tasks:
  - debug:
      msg: "{{ groups['postgres_secondary'] | map('extract', hostvars, ['networkInterfaces']) |  map('first') | map(attribute='networkIP') | join(',') }}"

  - debug:
      msg: "{{ ((groups['postgres_primary'] + groups['postgres_secondary']) | length) + 1 }}"

  - debug:
      msg: "{{ consul_ips | join(',') }}"

  - debug:
      msg: "{{ (pgbouncer_password + 'pgbouncer') | md5 }}"