---
- hosts: all:!ungrouped

  tasks:
    - name: Uninstall GitLab Omnibus
      become: true
      include_role:
        name: common
        tasks_from: uninstall
      when:
        - omnibus_node

    - name: Uninstall GitLab Charts
      become: false
      delegate_to: localhost
      include_role:
        name: gitlab-charts
        tasks_from: uninstall
      when:
        - cloud_native_hybrid_environment
