---
- name: Mount GitLab NFS
  mount:
    fstype: nfs
    opts: defaults,nofail,lookupcache=positive
    state: mounted
    src: "{{ gitlab_nfs_int_ip }}:{{ gitlab_nfs_path }}"
    path: "{{ gitlab_nfs_path }}"
  tags: nfs

- name: Remove old Jaeger container
  docker_container:
    name: jaeger
    state: absent
  tags:
    - reconfigure
    - restart

- name: Start Jaeger Docker
  docker_container:
    name: jaeger
    image: jaegertracing/all-in-one
    pull: true
    restart_policy: always
    state: started
    ports: ['5775:5775/udp', '6831:6831/udp', '5778:5778', '16686:16686', '14268:14268', '9411:9411']
    env:
      COLLECTOR_ZIPKIN_HTTP_PORT: '9411'
  tags:
    - reconfigure
    - restart

- name: Register Prometheus Consul services with the local consul agent
  include_role:
    name: consul-agent
  vars:
    prometheus_exporters:
      - service: node-exporter
        port: 9100
