---
- name: Install Docker Prerequisites
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2' ,'software-properties-common']

- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

- name: Install Docker
  apt:
    name: docker-ce
    update_cache: yes

- name: Remove old Jaeger container
  shell: "docker rm -f jaeger 2>/dev/null || true"
  ignore_errors: true
  tags: reconfigure

- name: Start Jaeger Docker
  shell: |
    docker pull jaegertracing/all-in-one
    docker run -d --name jaeger -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 -p 5775:5775/udp -p 6831:6831/udp -p 6832:6832/udp -p 5778:5778 -p 16686:16686 -p 14268:14268 -p 9411:9411 jaegertracing/all-in-one
  tags: reconfigure

