- name: Configure Deletion Adjourned period
  uri:
    url: '{{ external_url_sanitised }}/api/v4/application/settings'
    method: PUT
    headers:
      PRIVATE-TOKEN: '{{ access_token_key }}'
    body:
      deletion_adjourned_period: 0
    follow_redirects: all
    validate_certs: false
    status_code: 200, 201
    body_format: json
  register: result
  until: result is success
  retries: 5
  delay: 10

- name: Disable Limits
  uri:
    url: '{{ external_url_sanitised }}/api/v4/application/settings'
    method: PUT
    headers:
      PRIVATE-TOKEN: '{{ access_token_key }}'
    body:
      issues_create_limit: 0
      raw_blob_request_limit: 0
      max_import_size: 10240  # https://gitlab.com/gitlab-org/gitlab/-/issues/259801
    follow_redirects: all
    validate_certs: false
    status_code: 200, 201
    body_format: json
  register: result
  until: result is success
  retries: 5
  delay: 10

- name: Disable User Signup
  uri:
    url: '{{ external_url_sanitised }}/api/v4/application/settings'
    method: PUT
    headers:
      PRIVATE-TOKEN: '{{ access_token_key }}'
    body:
      signup_enabled: false
    follow_redirects: all
    validate_certs: false
    status_code: 200, 201
    body_format: json
  register: result
  until: result is success
  retries: 5
  delay: 10

- name: Disable Write to "authorized_keys" file setting
  uri:
    url: '{{ external_url_sanitised }}/api/v4/application/settings'
    method: PUT
    headers:
      PRIVATE-TOKEN: '{{ access_token_key }}'
    body:
      authorized_keys_enabled: false
    follow_redirects: all
    validate_certs: false
    status_code: 200, 201
    body_format: json
  register: result
  until: result is success
  retries: 5
  delay: 10

- name: Run custom API tasks
  block:
    - name: Check if Custom Config API tasks file exists
      stat:
        path: "{{ post_configure_api_tasks_file }}"
      register: post_configure_api_tasks_file_path

    - name: Run Custom Config API tasks
      include_tasks: "{{ post_configure_api_tasks_file }}"
      when: post_configure_api_tasks_file_path.stat.exists
  tags:
    - reconfigure
