- name: Disable Write to "authorized_keys" file setting
  uri:
    url: '{{ external_url_sanitised }}/api/v4/application/settings'
    method: PUT
    headers:
      PRIVATE-TOKEN: '{{ access_token_key }}'
    body:
      authorized_keys_enabled: false
    follow_redirects: all
    validate_certs: false
    status_code: 200, 201
    body_format: json
